// Municipios de Venezuela (335). Los ids coinciden con la tabla `township` de la
// base de datos (seeds/catalog/007-insert-zulia-townships.sql para Zulia, ids
// 1-21; 014-insert-rest-townships.sql para el resto, ids 22-335).
// `stateId` corresponde a `township.township_state_id` — ver state.catalog.ts.
export interface Township {
  id: number;
  name: string;
  stateId: number;
}

export const TOWNSHIPS: Township[] = [
  { id: 1, name: "Almirante Padilla", stateId: 24 },
  { id: 2, name: "Baralt", stateId: 24 },
  { id: 3, name: "Cabimas", stateId: 24 },
  { id: 4, name: "Catatumbo", stateId: 24 },
  { id: 5, name: "Colón", stateId: 24 },
  { id: 6, name: "Francisco Javier Pulgar", stateId: 24 },
  { id: 7, name: "Guajira", stateId: 24 },
  { id: 8, name: "Jesús Enrique Lossada", stateId: 24 },
  { id: 9, name: "Jesús María Semprún", stateId: 24 },
  { id: 10, name: "La Cañada de Urdaneta", stateId: 24 },
  { id: 11, name: "Lagunillas", stateId: 24 },
  { id: 12, name: "Machiques de Perijá", stateId: 24 },
  { id: 13, name: "Mara", stateId: 24 },
  { id: 14, name: "Maracaibo", stateId: 24 },
  { id: 15, name: "Miranda", stateId: 24 },
  { id: 16, name: "Rosario de Perijá", stateId: 24 },
  { id: 17, name: "San Francisco", stateId: 24 },
  { id: 18, name: "Santa Rita", stateId: 24 },
  { id: 19, name: "Simón Bolívar", stateId: 24 },
  { id: 20, name: "Sucre", stateId: 24 },
  { id: 21, name: "Valmore Rodríguez", stateId: 24 },
  { id: 22, name: "Atures", stateId: 1 },
  { id: 23, name: "Autana", stateId: 1 },
  { id: 24, name: "Atabapo", stateId: 1 },
  { id: 25, name: "Alto Orinoco", stateId: 1 },
  { id: 26, name: "Manapiare", stateId: 1 },
  { id: 27, name: "Río Negro", stateId: 1 },
  { id: 28, name: "Maroa", stateId: 1 },
  { id: 29, name: "Simón Bolívar", stateId: 2 },
  { id: 30, name: "Juan Antonio Sotillo", stateId: 2 },
  { id: 31, name: "Simón Rodríguez", stateId: 2 },
  { id: 32, name: "Francisco de Miranda", stateId: 2 },
  { id: 33, name: "Independencia", stateId: 2 },
  { id: 34, name: "Anaco", stateId: 2 },
  { id: 35, name: "Pedro María Freites", stateId: 2 },
  { id: 36, name: "San José de Guanipa", stateId: 2 },
  { id: 37, name: "Diego Bautista Urbaneja", stateId: 2 },
  { id: 38, name: "Guanta", stateId: 2 },
  { id: 39, name: "Aragua", stateId: 2 },
  { id: 40, name: "Píritu", stateId: 2 },
  { id: 41, name: "Manuel Ezequiel Bruzual", stateId: 2 },
  { id: 42, name: "Libertad", stateId: 2 },
  { id: 43, name: "Fernando Peñalver", stateId: 2 },
  { id: 44, name: "José Gregorio Monagas", stateId: 2 },
  { id: 45, name: "Juan Manuel Cajigal", stateId: 2 },
  { id: 46, name: "Francisco del Carmen Carvajal", stateId: 2 },
  { id: 47, name: "Sir Arthur McGregor", stateId: 2 },
  { id: 48, name: "Santa Ana", stateId: 2 },
  { id: 49, name: "San Juan de Capistrano", stateId: 2 },
  { id: 50, name: "Páez", stateId: 3 },
  { id: 51, name: "San Fernando", stateId: 3 },
  { id: 52, name: "Biruaca", stateId: 3 },
  { id: 53, name: "Achaguas", stateId: 3 },
  { id: 54, name: "Pedro Camejo", stateId: 3 },
  { id: 55, name: "Muñoz", stateId: 3 },
  { id: 56, name: "Rómulo Gallegos", stateId: 3 },
  { id: 57, name: "Sucre", stateId: 4 },
  { id: 58, name: "Girardot", stateId: 4 },
  { id: 59, name: "Libertador", stateId: 4 },
  { id: 60, name: "Zamora", stateId: 4 },
  { id: 61, name: "Santiago Mariño", stateId: 4 },
  { id: 62, name: "José Félix Ribas", stateId: 4 },
  { id: 63, name: "Mario Briceño Iragorry", stateId: 4 },
  { id: 64, name: "Urdaneta", stateId: 4 },
  { id: 65, name: "Francisco Linares Alcántara", stateId: 4 },
  { id: 66, name: "Bolívar", stateId: 4 },
  { id: 67, name: "José Rafael Revenga", stateId: 4 },
  { id: 68, name: "Santos Michelena", stateId: 4 },
  { id: 69, name: "Tovar", stateId: 4 },
  { id: 70, name: "José Ángel Lamas", stateId: 4 },
  { id: 71, name: "San Sebastián", stateId: 4 },
  { id: 72, name: "San Casimiro", stateId: 4 },
  { id: 73, name: "Camatagua", stateId: 4 },
  { id: 74, name: "Ocumare de la Costa de Oro", stateId: 4 },
  { id: 75, name: "Barinas", stateId: 5 },
  { id: 76, name: "Antonio José de Sucre", stateId: 5 },
  { id: 77, name: "Pedraza", stateId: 5 },
  { id: 78, name: "Ezequiel Zamora", stateId: 5 },
  { id: 79, name: "Bolívar", stateId: 5 },
  { id: 80, name: "Andrés Eloy Blanco", stateId: 5 },
  { id: 81, name: "Arismendi", stateId: 5 },
  { id: 82, name: "Rojas", stateId: 5 },
  { id: 83, name: "Alberto Arvelo Torrealba", stateId: 5 },
  { id: 84, name: "Obispos", stateId: 5 },
  { id: 85, name: "Sosa", stateId: 5 },
  { id: 86, name: "Cruz Paredes", stateId: 5 },
  { id: 87, name: "Sucre", stateId: 6 },
  { id: 88, name: "Caroní", stateId: 6 },
  { id: 89, name: "Heres", stateId: 6 },
  { id: 90, name: "Piar", stateId: 6 },
  { id: 91, name: "Cedeño", stateId: 6 },
  { id: 92, name: "Angostura", stateId: 6 },
  { id: 93, name: "Gran Sabana", stateId: 6 },
  { id: 94, name: "Sifontes", stateId: 6 },
  { id: 95, name: "El Callao", stateId: 6 },
  { id: 96, name: "Roscio", stateId: 6 },
  { id: 97, name: "Padre Pedro Chien", stateId: 6 },
  { id: 98, name: "Valencia", stateId: 7 },
  { id: 99, name: "Libertador", stateId: 7 },
  { id: 100, name: "Miranda", stateId: 7 },
  { id: 101, name: "Guacara", stateId: 7 },
  { id: 102, name: "Puerto Cabello", stateId: 7 },
  { id: 103, name: "Naguanagua", stateId: 7 },
  { id: 104, name: "Los Guayos", stateId: 7 },
  { id: 105, name: "Carlos Arvelo", stateId: 7 },
  { id: 106, name: "Diego Ibarra", stateId: 7 },
  { id: 107, name: "San Diego", stateId: 7 },
  { id: 108, name: "San Joaquín", stateId: 7 },
  { id: 109, name: "Juan José Mora", stateId: 7 },
  { id: 110, name: "Bejuma", stateId: 7 },
  { id: 111, name: "Montalbán", stateId: 7 },
  { id: 112, name: "Girardot", stateId: 8 },
  { id: 113, name: "San Carlos", stateId: 8 },
  { id: 114, name: "Tinaquillo", stateId: 8 },
  { id: 115, name: "Tinaco", stateId: 8 },
  { id: 116, name: "Rómulo Gallegos", stateId: 8 },
  { id: 117, name: "Pao de San Juan Bautista", stateId: 8 },
  { id: 118, name: "Ricaurte", stateId: 8 },
  { id: 119, name: "Anzoátegui", stateId: 8 },
  { id: 120, name: "Lima Blanco", stateId: 8 },
  { id: 121, name: "Tucupita", stateId: 9 },
  { id: 122, name: "Antonio Díaz", stateId: 9 },
  { id: 123, name: "Casacoima", stateId: 9 },
  { id: 124, name: "Pedernales", stateId: 9 },
  { id: 125, name: "Libertador", stateId: 10 },
  { id: 126, name: "Sucre", stateId: 11 },
  { id: 127, name: "San Francisco", stateId: 11 },
  { id: 128, name: "Carirubana", stateId: 11 },
  { id: 129, name: "Miranda", stateId: 11 },
  { id: 130, name: "Zamora", stateId: 11 },
  { id: 131, name: "Bolívar", stateId: 11 },
  { id: 132, name: "Falcón", stateId: 11 },
  { id: 133, name: "Los Taques", stateId: 11 },
  { id: 134, name: "Colina", stateId: 11 },
  { id: 135, name: "Silva", stateId: 11 },
  { id: 136, name: "Mauroa", stateId: 11 },
  { id: 137, name: "Píritu", stateId: 11 },
  { id: 138, name: "Federación", stateId: 11 },
  { id: 139, name: "Dabajuro", stateId: 11 },
  { id: 140, name: "Buchivacoa", stateId: 11 },
  { id: 141, name: "Acosta", stateId: 11 },
  { id: 142, name: "Unión", stateId: 11 },
  { id: 143, name: "Monseñor Iturriza", stateId: 11 },
  { id: 144, name: "Petit", stateId: 11 },
  { id: 145, name: "Jacura", stateId: 11 },
  { id: 146, name: "Democracia", stateId: 11 },
  { id: 147, name: "Cacique Manaure", stateId: 11 },
  { id: 148, name: "Urumaco", stateId: 11 },
  { id: 149, name: "Tocópero", stateId: 11 },
  { id: 150, name: "Palma Sola", stateId: 11 },
  { id: 151, name: "José Félix Ribas", stateId: 12 },
  { id: 152, name: "Juan Germán Roscio", stateId: 12 },
  { id: 153, name: "Leonardo Infante", stateId: 12 },
  { id: 154, name: "Sebastián Francisco de Miranda", stateId: 12 },
  { id: 155, name: "Pedro Zaraza", stateId: 12 },
  { id: 156, name: "José Tadeo Monagas", stateId: 12 },
  { id: 157, name: "Camaguán", stateId: 12 },
  { id: 158, name: "Julián Mellado", stateId: 12 },
  { id: 159, name: "Ortiz", stateId: 12 },
  { id: 160, name: "Las Mercedes", stateId: 12 },
  { id: 161, name: "Santa María de Ipire", stateId: 12 },
  { id: 162, name: "El Socorro", stateId: 12 },
  { id: 163, name: "Chaguaramas", stateId: 12 },
  { id: 164, name: "San Gerónimo de Guayabal", stateId: 12 },
  { id: 165, name: "San José de Guaribe", stateId: 12 },
  { id: 166, name: "Iribarren", stateId: 13 },
  { id: 167, name: "Torres", stateId: 13 },
  { id: 168, name: "Palavecino", stateId: 13 },
  { id: 169, name: "Urdaneta", stateId: 13 },
  { id: 170, name: "Morán", stateId: 13 },
  { id: 171, name: "Jiménez", stateId: 13 },
  { id: 172, name: "Crespo", stateId: 13 },
  { id: 173, name: "Andrés Eloy Blanco", stateId: 13 },
  { id: 174, name: "Simón Planas", stateId: 13 },
  { id: 175, name: "Sucre", stateId: 14 },
  { id: 176, name: "Libertador", stateId: 14 },
  { id: 177, name: "Miranda", stateId: 14 },
  { id: 178, name: "Alberto Adriani", stateId: 14 },
  { id: 179, name: "Campo Elías", stateId: 14 },
  { id: 180, name: "Tulio Febres Cordero", stateId: 14 },
  { id: 181, name: "Tovar", stateId: 14 },
  { id: 182, name: "Obispo Ramos de Lora", stateId: 14 },
  { id: 183, name: "Caracciolo Parra Olmedo", stateId: 14 },
  { id: 184, name: "Antonio Pinto Salinas", stateId: 14 },
  { id: 185, name: "Rivas Dávila", stateId: 14 },
  { id: 186, name: "Andrés Bello", stateId: 14 },
  { id: 187, name: "Rangel", stateId: 14 },
  { id: 188, name: "Santos Marquina", stateId: 14 },
  { id: 189, name: "Julio César Salas", stateId: 14 },
  { id: 190, name: "Arzobispo Chacón", stateId: 14 },
  { id: 191, name: "Zea", stateId: 14 },
  { id: 192, name: "Pueblo Llano", stateId: 14 },
  { id: 193, name: "Guaraque", stateId: 14 },
  { id: 194, name: "Cardenal Quintero", stateId: 14 },
  { id: 195, name: "Justo Briceño", stateId: 14 },
  { id: 196, name: "Aricagua", stateId: 14 },
  { id: 197, name: "Padre Noguera", stateId: 14 },
  { id: 198, name: "Sucre", stateId: 15 },
  { id: 199, name: "Baruta", stateId: 15 },
  { id: 200, name: "Simón Bolívar", stateId: 15 },
  { id: 201, name: "Guaicaipuro", stateId: 15 },
  { id: 202, name: "Plaza", stateId: 15 },
  { id: 203, name: "Páez", stateId: 15 },
  { id: 204, name: "Zamora", stateId: 15 },
  { id: 205, name: "Lander", stateId: 15 },
  { id: 206, name: "Independencia", stateId: 15 },
  { id: 207, name: "Urdaneta", stateId: 15 },
  { id: 208, name: "Chacao", stateId: 15 },
  { id: 209, name: "Paz Castillo", stateId: 15 },
  { id: 210, name: "Cristóbal Rojas", stateId: 15 },
  { id: 211, name: "El Hatillo", stateId: 15 },
  { id: 212, name: "Los Salias", stateId: 15 },
  { id: 213, name: "Acevedo", stateId: 15 },
  { id: 214, name: "Carrizal", stateId: 15 },
  { id: 215, name: "Brión", stateId: 15 },
  { id: 216, name: "Buroz", stateId: 15 },
  { id: 217, name: "Pedro Gual", stateId: 15 },
  { id: 218, name: "Andrés Bello", stateId: 15 },
  { id: 219, name: "Maturín", stateId: 16 },
  { id: 220, name: "Sotillo", stateId: 16 },
  { id: 221, name: "Libertador", stateId: 16 },
  { id: 222, name: "Piar", stateId: 16 },
  { id: 223, name: "Cedeño", stateId: 16 },
  { id: 224, name: "Ezequiel Zamora", stateId: 16 },
  { id: 225, name: "Bolívar", stateId: 16 },
  { id: 226, name: "Caripe", stateId: 16 },
  { id: 227, name: "Punceres", stateId: 16 },
  { id: 228, name: "Acosta", stateId: 16 },
  { id: 229, name: "Aguasay", stateId: 16 },
  { id: 230, name: "Santa Bárbara", stateId: 16 },
  { id: 231, name: "Uracoa", stateId: 16 },
  { id: 232, name: "Mariño", stateId: 17 },
  { id: 233, name: "García", stateId: 17 },
  { id: 234, name: "Maneiro", stateId: 17 },
  { id: 235, name: "Arismendi", stateId: 17 },
  { id: 236, name: "Díaz", stateId: 17 },
  { id: 237, name: "Gómez", stateId: 17 },
  { id: 238, name: "Marcano", stateId: 17 },
  { id: 239, name: "Tubores", stateId: 17 },
  { id: 240, name: "Antolín del Campo", stateId: 17 },
  { id: 241, name: "Península de Macanao", stateId: 17 },
  { id: 242, name: "Villalba", stateId: 17 },
  { id: 243, name: "Sucre", stateId: 18 },
  { id: 244, name: "Páez", stateId: 18 },
  { id: 245, name: "Guanare", stateId: 18 },
  { id: 246, name: "Araure", stateId: 18 },
  { id: 247, name: "Turén", stateId: 18 },
  { id: 248, name: "Esteller", stateId: 18 },
  { id: 249, name: "Guanarito", stateId: 18 },
  { id: 250, name: "Ospino", stateId: 18 },
  { id: 251, name: "San Genaro de Boconoíto", stateId: 18 },
  { id: 252, name: "Agua Blanca", stateId: 18 },
  { id: 253, name: "José Vicente de Unda", stateId: 18 },
  { id: 254, name: "San Rafael de Onoto", stateId: 18 },
  { id: 255, name: "Santa Rosalía", stateId: 18 },
  { id: 256, name: "Papelón", stateId: 18 },
  { id: 257, name: "Sucre", stateId: 19 },
  { id: 258, name: "Libertador", stateId: 19 },
  { id: 259, name: "Bermúdez", stateId: 19 },
  { id: 260, name: "Mariño", stateId: 19 },
  { id: 261, name: "Bolívar", stateId: 19 },
  { id: 262, name: "Montes", stateId: 19 },
  { id: 263, name: "Ribero", stateId: 19 },
  { id: 264, name: "Andrés Eloy Blanco", stateId: 19 },
  { id: 265, name: "Arismendi", stateId: 19 },
  { id: 266, name: "Cruz Salmerón Acosta", stateId: 19 },
  { id: 267, name: "Benítez", stateId: 19 },
  { id: 268, name: "Valdez", stateId: 19 },
  { id: 269, name: "Andrés Mata", stateId: 19 },
  { id: 270, name: "Cajigal", stateId: 19 },
  { id: 271, name: "Mejía", stateId: 19 },
  { id: 272, name: "Sucre", stateId: 20 },
  { id: 273, name: "San Cristóbal", stateId: 20 },
  { id: 274, name: "Libertador", stateId: 20 },
  { id: 275, name: "Simón Rodríguez", stateId: 20 },
  { id: 276, name: "Francisco de Miranda", stateId: 20 },
  { id: 277, name: "Independencia", stateId: 20 },
  { id: 278, name: "Cárdenas", stateId: 20 },
  { id: 279, name: "Jáuregui", stateId: 20 },
  { id: 280, name: "Junín", stateId: 20 },
  { id: 281, name: "Bolívar", stateId: 20 },
  { id: 282, name: "García de Hevia", stateId: 20 },
  { id: 283, name: "Ayacucho", stateId: 20 },
  { id: 284, name: "Pedro María Ureña", stateId: 20 },
  { id: 285, name: "Torbes", stateId: 20 },
  { id: 286, name: "Guásimos", stateId: 20 },
  { id: 287, name: "Fernández Feo", stateId: 20 },
  { id: 288, name: "Córdoba", stateId: 20 },
  { id: 289, name: "Panamericano", stateId: 20 },
  { id: 290, name: "Libertad", stateId: 20 },
  { id: 291, name: "Andrés Bello", stateId: 20 },
  { id: 292, name: "Michelena", stateId: 20 },
  { id: 293, name: "Uribante", stateId: 20 },
  { id: 294, name: "Samuel Darío Maldonado", stateId: 20 },
  { id: 295, name: "Lobatera", stateId: 20 },
  { id: 296, name: "José María Vargas", stateId: 20 },
  { id: 297, name: "Seboruco", stateId: 20 },
  { id: 298, name: "Antonio Rómulo Costa", stateId: 20 },
  { id: 299, name: "San Judas Tadeo", stateId: 20 },
  { id: 300, name: "Rafael Urdaneta", stateId: 20 },
  { id: 301, name: "Sucre", stateId: 21 },
  { id: 302, name: "Miranda", stateId: 21 },
  { id: 303, name: "Valera", stateId: 21 },
  { id: 304, name: "Urdaneta", stateId: 21 },
  { id: 305, name: "Boconó", stateId: 21 },
  { id: 306, name: "Trujillo", stateId: 21 },
  { id: 307, name: "San Rafael de Carvajal", stateId: 21 },
  { id: 308, name: "Bolívar", stateId: 21 },
  { id: 309, name: "Pampán", stateId: 21 },
  { id: 310, name: "Candelaria", stateId: 21 },
  { id: 311, name: "Escuque", stateId: 21 },
  { id: 312, name: "Carache", stateId: 21 },
  { id: 313, name: "Pampanito", stateId: 21 },
  { id: 314, name: "La Ceiba", stateId: 21 },
  { id: 315, name: "Motatán", stateId: 21 },
  { id: 316, name: "Rafael Rangel", stateId: 21 },
  { id: 317, name: "Andrés Bello", stateId: 21 },
  { id: 318, name: "Monte Carmelo", stateId: 21 },
  { id: 319, name: "Juan Vicente Campo Elías", stateId: 21 },
  { id: 320, name: "José Felipe Márquez Cañizalez", stateId: 21 },
  { id: 321, name: "Vargas", stateId: 22 },
  { id: 322, name: "Sucre", stateId: 23 },
  { id: 323, name: "Independencia", stateId: 23 },
  { id: 324, name: "San Felipe", stateId: 23 },
  { id: 325, name: "Peña", stateId: 23 },
  { id: 326, name: "Bruzual", stateId: 23 },
  { id: 327, name: "Nirgua", stateId: 23 },
  { id: 328, name: "Bolívar", stateId: 23 },
  { id: 329, name: "Cocorote", stateId: 23 },
  { id: 330, name: "Veroes", stateId: 23 },
  { id: 331, name: "Arístides Bastidas", stateId: 23 },
  { id: 332, name: "José Antonio Páez", stateId: 23 },
  { id: 333, name: "Manuel Monge", stateId: 23 },
  { id: 334, name: "Urachiche", stateId: 23 },
  { id: 335, name: "La Trinidad", stateId: 23 },
];

// Índice por estado, ordenado alfabéticamente, listo para alimentar un <select>.
export const townshipsByState: Record<
  number,
  { value: number; label: string }[]
> = TOWNSHIPS.reduce<Record<number, { value: number; label: string }[]>>(
  (acc, t) => {
    (acc[t.stateId] ??= []).push({ value: t.id, label: t.name });
    return acc;
  },
  {},
);

for (const options of Object.values(townshipsByState)) {
  options.sort((a, b) => a.label.localeCompare(b.label, "es"));
}

// Lookup por id para resolver el nombre de un municipio recibido del backend.
export const TOWNSHIP_BY_ID: Record<number, Township> = Object.fromEntries(
  TOWNSHIPS.map((t) => [t.id, t]),
);
