export const townships: { label: string; value: number }[] = [
  { label: "Almirante Padilla", value: 1 },
  { label: "Baralt", value: 2 },
  { label: "Cabimas", value: 3 },
  { label: "Catatumbo", value: 4 },
  { label: "Colón", value: 5 },
  { label: "Francisco Javier Pulgar", value: 6 },
  { label: "Guajira", value: 7 },
  { label: "Jesús Enrique Lossada", value: 8 },
  { label: "Jesús María Semprún", value: 9 },
  { label: "La Cañada de Urdaneta", value: 10 },
  { label: "Lagunillas", value: 11 },
  { label: "Machiques de Perijá", value: 12 },
  { label: "Mara", value: 13 },
  { label: "Maracaibo", value: 14 },
  { label: "Miranda", value: 15 },
  { label: "Rosario de Perijá", value: 16 },
  { label: "San Francisco", value: 17 },
  { label: "Santa Rita", value: 18 },
  { label: "Simón Bolívar", value: 19 },
  { label: "Sucre", value: 20 },
  { label: "Valmore Rodríguez", value: 21 },
];
